# Generated by Django 5.0.3 on 2024-05-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
        migrations.AlterModelTable(
            name='autoentrepreneur',
            table='auto_entrepreneur',
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='demande',
            table='demande',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
    ]
