# Generated by Django 5.0.6 on 2024-05-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_platform', '0003_delete_admin_remove_autoentrepreneur_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoentrepreneur',
            old_name='telephone',
            new_name='tel',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='telephone',
            new_name='tel',
        ),
        migrations.AddField(
            model_name='autoentrepreneur',
            name='firstName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='autoentrepreneur',
            name='lastName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='firstName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='lastName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.FileField(default='', upload_to='photos'),
        ),
    ]
