# Generated by Django 5.0.3 on 2024-05-28 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_platform', '0005_remove_demande_date_remove_service_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service_files')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='freelancers_platform.service')),
            ],
            options={
                'db_table': 'service_file',
            },
        ),
    ]
