# Generated by Django 5.0.3 on 2024-06-15 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_platform', '0006_servicefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('street', models.CharField(default='', max_length=255)),
                ('postalcode', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'adresse',
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='file',
        ),
        migrations.AlterField(
            model_name='servicefile',
            name='file',
            field=models.FileField(upload_to='service_files/'),
        ),
        migrations.AlterField(
            model_name='autoentrepreneur',
            name='adresse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelancers_platform.adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelancers_platform.adresse'),
        ),
    ]
