# Generated by Django 5.0.3 on 2024-06-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers_platform', '0008_alter_adresse_city_alter_adresse_postalcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='entrepreneur',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rate',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
